#!/bin/bash

# Copyright 2021 Melwyn Francis Carlo <carlo.melwyn@outlook.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd ..

java \
--module-path openjfx/linux/sdk \
--add-modules javafx.graphics,javafx.fxml,javafx.controls \
TypingPracticeAndTest.App

cd setup

